### ISSUE TITLE
CreateBackgroundServiceAsync

### ISSUE THREAD

**Issue by hevilhuy** [Tewr/BlazorWorker#109]
For somehow CreateBackgroundServiceAsync takes forever and not returning anything.
Steps to reproduce:
- Install NuGet package.
- Update Program.cs.
- Create class MyCPUIntensiveService.
- var test = await _worker.CreateBackgroundServiceAsync<MyCPUIntensiveService>();

**Comment by Ali-YousefiTelori** [comment]
How did you fix this?

**Comment by hevilhuy** [comment]
I just abandoned it.
