### ISSUE TITLE
IoC Example Doesn't Correctly Support Singletons

### ISSUE THREAD

**Issue by wbaldoumas** [Tewr/BlazorWorker#114]
I'm working on a project where I'm trying to create a background worker which ultimately updates Redux state using [Fluxor](https://github.com/mrpmorris/Fluxor). Fluxor must be registered as a singleton in order to work properly in this project so that actions are dispatched, reduced, and update global state.

In the IoC example provided, a dedicated service collection and service provider is being created in your [MyServiceStartup](https://github.com/Tewr/BlazorWorker/blob/main/src/BlazorWorker.Demo.IoCExample/MyServiceStartup.cs) and [ServiceCollectionHelper](https://github.com/Tewr/BlazorWorker/blob/main/src/BlazorWorker.Demo.IoCExample/ServiceCollectionHelper.cs) which is separate from the main application container and singletons will be created a second time within the app since it's now working with two service providers.

What would be the proper path forward here?

**Comment by Tewr** [comment]
Hello. Thank you for your interest in the project.

I have some difficulties decrypting your question here.... What do you mean separate from the "main application container"? Do you mean the ioc instance in the UI blazor process? I will assume that for the rest of this post.

Keep in mind (I'm not sure if it's obvious from readme and/or examples) here that we are not really creating a new thread, we are creating a new _Process_. And then we simulate thread-like behaviour by remoting into that process.

So each process will absolutely have their own container. The different processes cannot easily share the notion of a singleton.

You should probably keep Fluxor  and it's ioc registrations in the blazor application/UI container, and then any code that communicates directly with Fluxor must run on the UI thread.

Any heavy lifting that you want to do in a worker sh ou uld be separated into a service that will run on the worker, and it should not know about Fluxor.

Something like this on the UI app:

```
async Task OnGenerateImageButtonPush(int width, int height){
  // Call the worker, do heavy work
   var imageUrl = await this.myWorkerService.GenerateImage(width, height);
// Update state with fluxor
   this.Dispatcher.Dispatch(new ImageGeneratedAction(imageUrl));
}
```

Let me know if that helps you

**Comment by wbaldoumas** [comment]
> Do you mean the ioc instance/ IServiceProvider in the UI blazor process? I will assume that for the rest of this post.

Exactly this! 😄

> So each process will absolutely have their own container. The different processes cannot easily share the notion of a singleton.

This was my worry / assumption, but thank you for confirming. Your answer totally covers my question here, so feel free to close this one out. I'll look into your suggestion, but will likely wait on https://github.com/dotnet/aspnetcore/issues/17730 if it doesn't look feasible to work in BlazorWorker right now. Thanks!

**Comment by Tewr** [comment]
While doing multi-process with the Fluxor library is probably possible, it doesn't seem easy at all. Could be an interesting project though.
