### ISSUE TITLE
External dll reference gives error

### ISSUE THREAD

**Issue by gitreagan** [Tewr/BlazorWorker#13]
Hello,
Thanks for sharing, this is very useful!

Is it possible to load external dll’s in the worker service methods? We have few math heavy simulation methods in an external dll, which takes several seconds to complete depending on the input measurements. I tried loading the dll but it gives below error. Have you done anything similar? Is it possible to use external dll’s? Please advise. Thank you!

`Test-Worker-Error; ex.Message:Could not load type of field 'TestProject.Services.TestCPUIntensiveService:bb' (0) due to: Could not load file or assembly 'CPUIntensiveService.Model, Version=0.2.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.; ex.StackTrace:  at BlazorWorker.BackgroundServiceFactory.WorkerBackgroundServiceProxy`1[T].InitAsync (BlazorWorker.Core.WorkerInitOptions workerInitOptions) <0x38f3160 + 0x00740> in <filename unknown>:0 
  at BlazorWorker.BackgroundServiceFactory.WorkerBackgroundServiceExtensions.CreateBackgroundServiceAsync[T] (BlazorWorker.Core.IWorker webWorkerProxy, BlazorWorker.Core.WorkerInitOptions workerInitOptions) <0x38c8820 + 0x00156> in <filename unknown>:0 
  at TestProject.Pages.TestPage.RunWorker () [0x001b9] in \TestProject\Pages\TestPage.razor:193`

**Comment by marcussacana** [comment]
An example adding references:
```csharp
var Worker = await Engine.Worker.CreateAsync();
var Service = await Worker.CreateBackgroundServiceAsync<YourClassHere>(new WorkerInitOptions(){
    DependentAssemblyFilenames = new[] { "MeReference1.dll",  "MeReference2.dll" }
});
```

**Comment by gitreagan** [comment]
That worked! Thanks for the quick response Marcus!
