### ISSUE TITLE
Switching pages while waiting for task to finish

### ISSUE THREAD

**Issue by Tewr** [Tewr/BlazorWorker#24]
_User jdcrutchley sends the following message to the owners of Package 'Tewr.BlazorWorker.BackgroundService 1.3.0'._

I'm looking to do something strange with Blazor, and was wondering if your BlazorWorker project might help me. I want to start a long set of API interactions that could take several minutes, but allow the user to switch pages and then come back and see progress or maybe a "finished" message if it is done. If I navigate away from my page and don't have a cancellation token set up, the async process continues in the background, but I don't know how to "hook back up" to it from the front end when the page reloads. Is this a use case that BlazorWorker could help with, or am I barking up the wrong tree?

Thanks.

jdc

**Comment by Tewr** [comment]
Hello,

If the only thing your Task is doing is waiting for a remote API to return a response, I'd say this library is clearly overkill.

I would encapsulate the call to the remote API in a service class, and let the service class save references to the tasks. This service could be injected and set up as Singleton. This way, when you navigate away and come back to the page, consult the saved tasks to check if they are finished.

**Comment by jdcrutchley** [comment]
Thank you for replying.  I actually figured that out shortly after sending message, but didn't want to bother you with another message saying "nevermind".  I'm still coming to grips with how user-scoped services can be singletons in blazor.
