### ISSUE TITLE
Blazorworker requesting missing assembly

### ISSUE THREAD

**Issue by bpyzik** [Tewr/BlazorWorker#26]
The blazorworker is requesting missing assembly Microsoft.AspNetCore.Components, Version=3.1.8.0 but I have that NuGet package installed. Interestingly, when installing version 3.1.9.0 the error changes to the same but lists the missing assembly as 3.1.9.0. How can I provide the blazorworker with this assembly?

**Comment by Tewr** [comment]
You need to explicitly specify the actual files containing the assemblies that your service class depends on. 

Ex:
```
var serviceInstance = await worker.CreateBackgroundServiceAsync<MyService>(
      options => options
          .AddConventionalAssemblyOfService()
          .AddAssemblies("Microsoft.AspNetCore.Components.dll")
  );
```
