### ISSUE TITLE
BlazorWorker.WorkerCore

### ISSUE THREAD

**Issue by BeatSkip** [Tewr/BlazorWorker#31]
Not sure if i'm doing something wrong, but i had to download the source and compile my own version of BlazorWorker.WorkerCore package to get IWorker to be included. Something is not working as it should.

![image](https://user-images.githubusercontent.com/12702701/101938964-939c2c00-3be4-11eb-8b89-2898952c14c6.png)

after publishing 
BlazorWorker.WorkerCore to a nuget package and including that from a local repository everything worked fine.
Still working on getting the whole thing working so not sure if that is good. But at least this should be fixed i think.

Great work on this nonetheless, awesome unique content with a lot of promise!

**Comment by Tewr** [comment]
I need some more info to reproduce this. I am working on getting a more extensive automated test suite up, but I didn't run into anything like this during manual testing. That said, the backgroundservice package does get a lot more love in testing than the core package.

What package version are you using? Are you targeting .Net5 ou netcore31?

**Comment by BeatSkip** [comment]
I'm using a (almost) clean .net 5.0 project. installed both blazorworker packages from nuget, added the required imports and the usual stuff. I can share a template project with the problem reproduced tomorrow if you want to. But it might be faster for you to just try it with a brand new project. I tried multiple things and could not use the workercore namespace until i compiled that myself

**Comment by Tewr** [comment]
Something confusion when multi-targeting was added, the wrong package ended up at nuget, dependencies was not included.. Package version 2.0.1 is OK.
