### ISSUE TITLE
IndexedDb / JsInterop

### ISSUE THREAD

**Issue by andersson09** [Tewr/BlazorWorker#33]
Is there a way for the worker to load javascript for JsInterop, specifically to get IndexedDb working?

I am currently using the package https://github.com/wtulloch/Blazor.IndexedDB and am able to resolve dependencies fine and return the IndexedDBManager.Name. However actually communicating with the db results in the process just hanging. I think this might be because we need to pass the interop script TG.Blazor.IndexedDB/indexedDb.Blazor.js somehow.

**Comment by Tewr** [comment]
Hello again

I've been down this road a few months ago, I was working on supporting `IJSRuntime` as an injectable service. But the upgrade to .NET 5 got in the way. In short, yes executing javascript in the worker context is *possible*. But it's not very pleasant atm. To get started you would have to copy or reflect your way into the following classes :

https://github.com/Tewr/BlazorWorker/blob/master/src/BlazorWorker.WorkerCore/DOMObject.cs
https://github.com/Tewr/BlazorWorker/blob/master/src/BlazorWorker.WorkerCore/WebAssemblyBindingsProxy/JSObject.cs
https://github.com/Tewr/BlazorWorker/blob/master/src/BlazorWorker.WorkerCore/WebAssemblyBindingsProxy/Runtime.cs

and then you could call methods like this: https://github.com/Tewr/BlazorWorker/blob/26240ebf6761203585d8f0a09981c76b14739b84/src/BlazorWorker.WorkerCore/MessageService.cs#L28

Then again, your script must be "worker" compatible ( it doesn't reference the "window" object directly etc)
If that is the case you could probably do `self.importScripts` on the script in question and it might work. But I'm curious on how you got managed to configure its dependencies without `IJSRuntime`...

**Comment by andersson09** [comment]
Hi again :) I don't see an ImportScripts method on the DOMObject, or do you mean 

    self.Invoke("importScripts", "./js/example.js");

In this case I receive : One or more errors occurred. (Member 'HelpURL' was not found.)

I only configured the dependencies since I was playing around with the default JsRuntime implementation.

Overall, I'm trying to implement IJsRuntime with your DOMObject so that interop will work for third party libraries such as IndexedDb.

**Comment by Tewr** [comment]
The IJSRuntime of Blazor leverages a serializer, something like `System.Text.Json` if I remember correctly. `DomObject` does no such thing, it's all native marshalling. For this library I have been working with strings only, and the notion of objects have been in dot net only.

I am guessing that the error you are seeing comes in part from these implementation details, but also the default implementation in blazor comes with underlying implementation in javascript.

**Comment by Tewr** [comment]
I think I can provide a crude version of implementing `IJSRuntime`. here https://github.com/wtulloch/Blazor.IndexedDB/blob/master/TG.Blazor.IndexedDb/IndexedDB/IndexedDBManager.cs only the simple `InvokeAsync(method, args)` is used. Which should be feasable, so at least indexedDb and other simple libraries would be supported. I'm going to skip jsreferences and other existing blazor features of the api for now as its a lot more work.

**Comment by andersson09** [comment]
awesome

**Comment by Tewr** [comment]
An alpha implementation of both JsInterop and IndexedDB will be included in the next release.

**Comment by andersson09** [comment]
> An alpha implementation of both JsInterop and IndexedDB will be included in the next release.

Great, can't wait to try this out!
