### ISSUE TITLE
Local wasm app works, but published wasm app does not.

### ISSUE THREAD

**Issue by dclamage** [Tewr/BlazorWorker#36]
So before installing the BlazorWorker nuget package, I wasn't having any issue with my published build, but after doing so and using the web worker for a new background process, it works perfectly in chrome when I run locally with Visual Studio, but when I actually use the dotnet publish command and host the result on my static website, I get a ton of missing dlls and the web worker does not work.

I use the following command to publish:
`dotnet publish ProjectName.csproj -c Release -o release --nologo`

When I try to use the web worker functionality on the published version, I get this exception:
`System.Runtime.Serialization.SerializationException: Error converting type: NoSetMethodForProperty, System.Runtime.Serialization.DateTimeOffsetAdapter, UtcDateTime`

Here's images of the missing dlls:
![image](https://user-images.githubusercontent.com/10701249/104580540-41e72700-5612-11eb-9e28-6e4669edda9f.png)
![image](https://user-images.githubusercontent.com/10701249/104580631-59beab00-5612-11eb-83a4-a6804c7e088b.png)

Any idea how I can resolve this?

**Comment by Tewr** [comment]
Hello! Thank you for your feedback!

The .NET5 support is fresh out of the oven and indeed, the linker is much more agressive than before. Still, I'll classify this as a bug. I didn't take the time to test publishing and I've hadn't had too much time for this  in general lately.

So for now you can either turn linking completely for publication, or create a specific linker config.

**Comment by Tewr** [comment]
But also there is the problem of noise in the console after trimming. this is an older problem with the linker that I haven't gotten around solving yet. In any case there is no point of trying to download a dll which does not exist, and normally the linker should update the manifest if it does any trimming. 

Unfortunately this is all quite painful to develop, as the build tools are still immature, i find myself restarting visual studio over and over and/or doing manual suppression of build output, to avoid bogus runtime errors on dll signatures

**Comment by dclamage** [comment]
For now, I've turned off trimming and it does resolve the issue, though of course it would be nice to benefit from trimming.

My project is open source and available at https://github.com/dclamage/Sudoku if you want to check anything about my project setup.

[Here's](https://github.com/dclamage/Sudoku/commit/e5c9b13efc026d58f03f5c7724b8b6d20c1dcbea) where I added a bunch of `<TrimmerRootAssembly>` configurations for all the missing dlls (including `System.Runtime.Serialization`) which prevented a lot of the missing dll errors but didn't fix the `SerializationException`.

[Here](https://github.com/dclamage/Sudoku/commit/ae16a585cf2a2d748c1c9d3903c36672785cdc70) I added even more dlls with the same result.

[And finally here](https://github.com/dclamage/Sudoku/commit/a781931b83129724f35e73d823e8c04e8c0fd32c) I disabled trimming entirely, which did fix the issue.

Thanks!

**Comment by dclamage** [comment]
I guess I should mention that if you want to test the web workers, load the base site and click this icon:
![image](https://user-images.githubusercontent.com/10701249/104827990-695c1080-5819-11eb-9686-6b257db247d2.png)

**Comment by taradinoc** [comment]
I had the same experience ([service defined here](https://foss.heptapod.net/zilf/zilf/-/blob/465691503399c2922d9b37a81007745036e716b2/src/Zilf.Playground/Services/Builds/BuildService.cs). Adding a `TrimmerRootAssembly` cleaned up some of the errors I was seeing in the console, but the `NoSetMethodForProperty, System.Runtime.Serialization.DateTimeOffsetAdapter, UtcDateTime` error persisted until I turned off trimming entirely.

**Comment by Tewr** [comment]
I've managed to reproduce the linking error, it was unexpectedly difficult though. I had to set both `PublishTrimmed=true` and `TrimMode=link`. I wonder if we have different defaults or something...

Some notes: Under my library, the top stack is `Serialize.Linq.Serializers.ExpressionSerializer.SerializeText`. 
Adding the following to the linker config of `WorkerBackgroundService `does not change the error message or anything, really.
```
  <assembly fullname="System.Runtime.Serialization" preserve="all"/>
  <assembly fullname="Serialize.Linq" preserve="all"/>
```

**Comment by Tewr** [comment]
Turns out all assemblies called `System.Runtime.Serialization` are empty placeholders in .NET5, and are using [type forwarding](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.typeforwardedtoattribute?view=net-5.0), a concept I didn't even knew existed... well you learn something new every day.
So our missing type is actually in `System.Private.DataContractSerialization`. I've added it to the a linker config and the error goes away.   @dclamage  I've tested your soduko resolver and it seems to work after I did this, and it should probably be OK to add this in a consuming project rather than in the library itself, so while you wait for me to produce a new release, you can probably use this workaround.

**Comment by dclamage** [comment]
Wow, thank you! I updated to your latest nuget release, removed the line from my project that disabled trimming, and everything works great now! No 404 errors in the console, and the WebWorker executes perfectly.
