### ISSUE TITLE
"System.ArgumentNullException: Value cannot be null" in WorkerInstanceManager.RegisterEvent

### ISSUE THREAD

**Issue by taradinoc** [Tewr/BlazorWorker#37]
_Originally posted by @Tewr in https://github.com/Tewr/BlazorWorker/issues/28#issuecomment-757541286_:

> @andersson09 I dont think this is related, more likely is that the worker process does not have the type `TEvent` (as in `EventHandler<TEvent>`)  loaded in memory. Please open a new issue if you want to discuss this further. I think an error message might be missing here in any case.

I'm running into the same problem when I use a custom event argument type (an enum I've defined). I suspect the cause is here:

https://github.com/Tewr/BlazorWorker/blob/c971af1af3259a564e783c8a305b6aa06e8e1a53/src/BlazorWorker.ServiceFactory/WorkerBackgroundServiceProxy.cs#L223

`Type.GetType` requires an assembly-qualified name when the type is defined anywhere except mscorlib or the current assembly (i.e., BlazorWorker.WorkerBackgroundService.dll), but `EventHandlerTypeArg` doesn't include the assembly name.

**Comment by Tewr** [comment]
I was able to reproduce, fixed in master, available in upcoming release.
