### ISSUE TITLE
integrity problem in published version net5.0

### ISSUE THREAD

**Issue by Blame4** [Tewr/BlazorWorker#44]
`(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://**********/_framework/Serialize.Linq.dll' with computed SHA-256 integrity 'VsDG9v5hAIf37tRPnT1Nqbu2cE9gPYyP5czUixcnYl8='. The resource has been blocked.`

Sometimes the Newtonsoft.Json has the same error.

Environment: WASM, host by httpsys as a windows service.
Only encountered in published version,

It's an old problem. I solve this problem by using the source code of this project. Change the targetframework to net5.0, and clean the solution, delete all the bin and obj directories. Update all the package. It works every time. Maybe it's the blazor problem. Before Blazor fix it, How about separate this project into net2.1 and net5.0 temporarily.

**Comment by Tewr** [comment]
I have had this problem but very sporadically, also in other unrelated Blazor projects. I don't think this has anything to do with multitargeting, however possibly trimming.  Do you see it all the time? I've always solved it simply by flushing the application cache in chrome, but occasionally I have had to resolve to deleting bin/obj like you say.

**Comment by Blame4** [comment]
Yeah, each time I tried to use nutget, the same problem in published the version.Then solved the problem as I said. Currently It's about two packages,newtonsoft.json and serialize.linq. I would have the same issue if I don't update the version of serialize.linq. I'm not bothered right now,because this project is open source.And Blazor is improving, need more testings.

**Comment by Tewr** [comment]
I'm closing this for now, feel free to open of there's anything to add to the discussion
