### ISSUE TITLE
how to disable message output in F12

### ISSUE THREAD

**Issue by xibaoning** [Tewr/BlazorWorker#54]
large byte[] to trans,  many large string output in debug window(F12), how to disable it , or config to disable output

Console.WriteLine($"{nameof(InjectableMessageService)}.{nameof(PostMessageAsync)}('{message}')"); //  how to disable
impleInstanceServiceProxy.class  and  InjectableMessageService.PostMessageAsync.class

**Comment by Tewr** [comment]
It should only be enabled in debug builds, I'll have a look
