### ISSUE TITLE
`AddBlazorWorkerJsRuntime` missing and `BlazorWorker.Extensions.JSRuntime` package isn't published

### ISSUE THREAD

**Issue by ElanHasson** [Tewr/BlazorWorker#59]
See: 

https://github.com/Tewr/BlazorWorker/blob/073c7b01e79319119947b427674b91804b784632/src/BlazorWorker.Demo.IoCExample/MyServiceStartup.cs#L28

The package `BlazorWorker.Extensions.JSRuntime` is missing from NuGet.

**Comment by Tewr** [comment]
Hello. Here it's is: https://www.nuget.org/packages/Tewr.BlazorWorker.Extensions.JSRuntime/1.0.1-preview

You might be missing it from the command line as it's in preview. Use the explicit version parameter: 

`Install-Package Tewr.BlazorWorker.Extensions.JSRuntime -Version 1.0.1-preview`

**Comment by ElanHasson** [comment]
Ahhh! Yes Preview :)
