### ISSUE TITLE
Exception: Unable to find compatible constructor for activating type 'My.WorkerStartup'.

### ISSUE THREAD

**Issue by ElanHasson** [Tewr/BlazorWorker#60]
When you do not register a type for the constructor of the Worker Startup class, you get an unclear error, even with `WorkerOptions.Debug` set to `true`.

It would be helpful if the error displayed the parameter that wasn't able to be resolved.

Additionally, in this case it was `IConfiguration` that was being injected. It would be great if the registrations from the `WebAssemblyHostBuilder.CreateDefault` were automatically included for you they aren't configured manually.

Source of exception: 
https://github.com/Tewr/BlazorWorker/blob/8a0611f8e25ca1cd92fdfe5b559d788d8ae34109/src/BlazorWorker.WorkerCore/SimpleInstanceService/SimpleInstanceService.cs#L200

**Comment by Tewr** [comment]
As discussed on twitter, there are some things that should be clearer in the readme: that only a fixed set of services get injected unless the factory methods are used.
