### ISSUE TITLE
Errors when using library

### ISSUE THREAD

**Issue by jasjae** [Tewr/BlazorWorker#63]
Folowing the instructions for the library, I get the errors below in the log. I have added all the assemblies I can think of as dependencies. 
Code:
`var worker = await _workerFactory.CreateAsync();
var service = await worker.CreateBackgroundServiceAsync<MyCPUIntensiveService>(
    options => options
        .AddConventionalAssemblyOfService()
        .AddAssemblies("Assm.Client", "Assm.Shared")
);
var result = await service.RunAsync(s => s.MyMethod2(docMgr, "123"));`

Errors:
a62b4eb3-d960-4b68-aae9-f344c72ecaa1:70 WASM-WORKER: undefined
Module.printErr @ a62b4eb3-d960-4b68-aae9-f344c72ecaa1:70
a62b4eb3-d960-4b68-aae9-f344c72ecaa1:28 Init method [BlazorWorker.WorkerBackgroundService]BlazorWorker.WorkerBackgroundService.WorkerInstanceManager:Init failed ReferenceError: showErrorNotification is not defined
    at Module.printErr (a62b4eb3-d960-4b68-aae9-f344c72ecaa1:71)
    at abort (dotnet.6.0.0-preview.7.21377.19.js:1)
    at _abort (dotnet.6.0.0-preview.7.21377.19.js:1)
    at dotnet.wasm:0x149430
    at dotnet.wasm:0x7e687
    at dotnet.wasm:0x66a5e
    at dotnet.wasm:0x168e10
    at dotnet.wasm:0x160079
    at dotnet.wasm:0xaca88
    at dotnet.wasm:0x1595d
onReady @ a62b4eb3-d960-4b68-aae9-f344c72ecaa1:28
a62b4eb3-d960-4b68-aae9-f344c72ecaa1:71 Uncaught (in promise) ReferenceError: showErrorNotification is not defined
    at Module.printErr (a62b4eb3-d960-4b68-aae9-f344c72ecaa1:71)
    at abort (dotnet.6.0.0-preview.7.21377.19.js:1)
    at _abort (dotnet.6.0.0-preview.7.21377.19.js:1)
    at dotnet.wasm:0x149430
    at dotnet.wasm:0x7e687
    at dotnet.wasm:0x66a5e
    at dotnet.wasm:0x168e10
    at dotnet.wasm:0x160079
    at dotnet.wasm:0xaca88
    at dotnet.wasm:0x1595d

**Comment by Tewr** [comment]
Hello. Assemblies should be dll names. Try replacing 
AddAssemblies("Assm.Client", "Assm.Shared")
With
AddAssemblies("Assm.Client.dll", "Assm.Shared.dll")
