### ISSUE TITLE
Any nuget-released planned including environment variable for culture?

### ISSUE THREAD

**Issue by mattincode** [Tewr/BlazorWorker#76]
Current nuget (3.1.0) doesn't include the possiblity to set web-worker environment variables like culture.
Issue: [#67](https://github.com/Tewr/BlazorWorker/issues/67)
This is a problem when needing to correctly format dates etc.
Since .NET 7 Threading support is still some time in the future this project is the only good option to use web-workers for more complex stuff using C#. Do you plan to do a new nuget-release anytime soon?

Excellent work by the way!

/Best Regards 
"Matt"

**Comment by Tewr** [comment]
done https://github.com/Tewr/BlazorWorker/releases/tag/v3.2.0
