### ISSUE TITLE
[Question] JS Invoke

### ISSUE THREAD

**Issue by marcussacana** [Tewr/BlazorWorker#8]
Can I invoke JS from my C# code in the worker service?
If yes, can you provide a small example of how?

**Comment by Tewr** [comment]
You could, but you would not be able to access the Dom directly.

The code central to this is in [message service]( https://github.com/Tewr/BlazorWorker/blob/1f999cf3b6f58a354525a197a6124da1373b4b8e/src/BlazorWorker.WorkerCore/MessageService.cs) but you also need the DomObject class which is in the same place, but is internal (just copy it and put it in you project and it should work

That said, it's not very interesting atm as you don't have access to neither Dom nor root object of the worker. You could call self.eval maybe

**Comment by Tewr** [comment]
What kind of interop did you have in mind? In the current version you could define an event that would call IJSRuntime of blazor, won't be super fast though if large amounts of data

**Comment by marcussacana** [comment]
in the true I want implement a shared memory to give to the Worker an byte[];
the serialization of the byte[] is freezing my app making everything meaningless.

**Comment by Tewr** [comment]
Ah. Well that's a very complex use case. I would like to implement streams using that, but the browser support is flaky atm, only chromium supports it, and edgium only since January. So I would have to test for availability and stuff, complex implementation. Probably why I didn't get to it yet.

The byte you want to serialize, where would you get it from? Reading a file? Indeed unmarshalled interop is the fastest way of doing that, but it could be without sharedarraybuffer, serialized in blocks, to avoid freezing

**Comment by marcussacana** [comment]
I have 3 sources from the data, one is downloading, one is from localstorage, and other is a genareted binary by the blazor.
I'm using the worker to do a compression in the binary data without hang the UI.
but since the file have few mbs of size, and I have around 55 files to decompress/compress, I want a more fast way to give the data to the worker thread.
I will use  the worker to compress/decompress the genareted data and downloaded one.

**Comment by marcussacana** [comment]
Well, I already got my answer, I think this issue is a duplicate of #3 So i will close it.
Also, very thanks for this awesome library, the multithreading is a very useful feature.

**Comment by Tewr** [comment]
Ok. This is more or less the use case I had in mind for #3 . I would imagine only exposing the stream interface, and the underlying implementation could use sharedarraybuffer if available. 

But exposing some kind of jsinterop service that could be used by workers would be interesting as well I guess.

Pull requests are welcome, If you figure something out in the meantime... But both the idea of memory sharing and Jsinterop have merit to be part of this project
