### ISSUE TITLE
nuget.org releases missing?

### ISSUE THREAD

**Issue by jon001** [Tewr/BlazorWorker#86]
I'm very confused by the releases available at nuget.org - the latest is 3.1.1 (which doesn't appear here), and there's no sign of 3.2.0 or 3.2.1. Have you moved away from nuget.org or is there something amiss somewhere?

**Comment by Tewr** [comment]
Hello. 3.2.0 was a core only release, which I admit is not very clear. Indeed 3.2.1 seems to be missing, I'll look into aligning the versions.

**Comment by Tewr** [comment]
versions are aligned in this tag and uploaded on nuget https://github.com/Tewr/BlazorWorker/releases/tag/v3.2.2

**Comment by jon001** [comment]
Lovely, thanks - nuget is giving me the goods now!
