### ISSUE TITLE
Net8 Support -- BlazorWorker: Unable to locate dotnetjs file in blazor boot

### ISSUE THREAD

**Issue by dodyg** [Tewr/BlazorWorker#90]
I found this error `BlazorWorker: Unable to locate dotnetjs file in blazor boot` at the web browser log. I am using .NET WASM 8 RC1. Do I miss anything? 

at Program.cs
``` csharp
services.AddWorkerFactory();
```

at Razor
``` csharp
public class NotificationService (IWorkerMessageService workerMessage)
{
    public async Task DoAsync()
    {
        await workerMessage.PostMessageAsync("Hello world");
    }
}

    protected override async Task OnInitializedAsync()
    {
        _worker = await workerFactory.CreateAsync();
        _worker.IncomingMessage += OnWorkerMessage;

        _backgroundService = await _worker.CreateBackgroundServiceAsync<NotificationService>();
        await _backgroundService.RunAsync(x => x.DoAsync());
    }

    void OnWorkerMessage(object? sender, string message)
    {
        Log($"Receive Message {message}", LogType.Error);
    }
```

**Comment by Tewr** [comment]
Yes most likely. The breaking changes of net7 are not likely to have been reverted in net 8

**Comment by Tewr** [comment]
This is a new breaking change in the bootstrapper. For net8 the blazorboot is reconstructed quite heavily with the runtime being split up in two files, dotnet.native.8.0.0.ot6jeefn53.js and dotnet.runtime.8.0.0.1khq4boqw1.js. I'm going to have to do some reading to solve this

**Comment by Tewr** [comment]
I've made some progress here tonight, but Crucial JsInterop fails without error
https://github.com/Tewr/BlazorWorker/pull/91

**Comment by TrixxTraxx** [comment]
I would really like this to be fixed.
Would it be possible to push a build that only supports syncronous workloads?

**Comment by Tewr** [comment]
I haven't been able to reproduce a fully working runtime even while avoiding the triggering of a task switch. Something is missing. 

This issue will post some kind of guide, might be useful but seems like they are planning for a demo using a separate template and a separate build, which is a bit sad, cause it's a lot more work

https://github.com/dotnet/runtime/issues/95452

**Comment by Tewr** [comment]
Some good news after climbing fown the rabbit hole: need more investigation but `await dotnet.run();` , which was introduced by me while testing .net7, seems to be the culprit. 

Seems to work fine after removing this line. Something has changed in .net8 which make this line break the runtime. In any case this line is useless as all it does is call Program.Main() which is needed for nothing.

If this is really the case, I might be able to get out a beta version in a few days

**Comment by pavelsavara** [comment]
> `await dotnet.run()`
> In any case this line is useless as all it does is call Program.Main() which is needed for nothing.

That is indeed just running main.

@maraf we should update our template to make it clear users don't have to call this.

> Something has changed in .net8 which make this line break the runtime. 

The change is that we will properly "exit" the "process" after main is finished.

**Comment by Tewr** [comment]
.net8 support works in https://github.com/Tewr/BlazorWorker/releases/tag/v4.0.0-preview2 , try it out.
