### ISSUE TITLE
Can I pass structured data to Worker?

### ISSUE THREAD

**Issue by yatsuna827** [Tewr/BlazorWorker#97]
Due to the complexity of the data passed to the worker, a record struct has been defined to pass it.

```cs
public record struct MyRequest(int A, int B, int C); // Actually has more arguments

...

var req = new MyRequest(a, b, c);
await service.RunAsync(s => s.Call(req));
```

However, this results in the following error:

> Unhandled exception rendering component: Error converting type: Type 'MyProject.MyRequest' with data contract name 'MyRequest:http://schemas.datacontract.org/2004/07/MyProject' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.

It seems like this error occurred because `MyRequest` was interpreted as different types of objects inside and outside the Worker.
I attempted to address this, but `AddAssemblies` has already been deprecated and noted to not work. Is there a way to workaround this issue?

**Comment by Tewr** [comment]
Hello.

`AddAssemblies()` is/was unrelated to what you are trying to do, it was simply a download size optimisation.

I cannot see the full call stack but I'm pretty sure this is the default json serializer of `Serialize.Linq` that needs additional configuration for certain types. Not much available today in the api achieve this unfortunately. There's an issue open on the subject since a while: #27 .

I've been trying to figure out something smart for this, but I'm also pretty sure there's a dumb/simple way for library consumers to configure serialization of expressions themselves .

I'll try to find the time to find a simple solution to #27 in the coming days. In the mean time, some complex types must be serialized to a string or byte array before being sent over the line.

**Comment by Tewr** [comment]
I'm confident this is linked to #27 , you can reopen I you think otherwise

**Comment by yatsuna827** [comment]
In case #27, it was speculated that IFileListEntry couldn't be serialized due to having references like Stream. However, what I'm attempting involves a simple Record struct composed solely of primitive elements, which doesn't seem to lack default serialization support.

From reading the error code, it appears that objects that should be the same are interpreted as belonging to different namespaces, causing deserialization failures.

Even tuples faced the same issue. Though the errors displayed are different, the root cause is likely the same.

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Error converting type: Type 'System.ValueTuple`2[[System.UInt32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.UInt32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' with data contract name 'ValueTupleOfunsignedIntunsignedInt:http://schemas.datacontract.org/2004/07/System' is not expected. Add any types not known statically to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding them to the list of known types passed to DataContractSerializer.
System.Runtime.Serialization.SerializationException: Error converting type: Type 'System.ValueTuple`2[[System.UInt32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.UInt32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutra…
blazor.webassembly.js:1:46998
```

Is the solution you are trying to find a way to fix this?

**Comment by Tewr** [comment]
The solution will be to expose a Type property that must implement  the interface that is used to serialize expressions. It's a bit more complex than classic json for example, as it requires the receiving end to have full type information.
